name: Terraform Apply

on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    apply:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          name: Checkout source code

        - uses: hashicorp/setup-terraform@v3
          name: Setup Terraform

        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.ARM_CLIENT_ID }}
            tenant-id: ${{ secrets.ARM_TENANT_ID }}
            subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

        - name: Terraform Init
          id: init
          run: terraform init
        
        - uses: terraform-cache/terraform-cache@v1

        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color
        
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color