name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    plan:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          name: Checkout source code

        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - uses: hashicorp/setup-terraform@v3
          name: Setup Terraform
            
        - uses: terraform-cache/terraform-cache@v1
        
        - name: Terraform Init
          id: init
          run: terraform init
        
        - name: Terraform Plan
          id: plan
          run: terraform plan -destroy

        - name: Terraform Destroy
          id: destroy
          run: terraform apply -auto-approve -destroy